export const cartActionTypes = {
  TOGGLE_CART_VISIBILITY: "TOGGLE_CART_VISIBILITY",
  ADD_CART_ITEM: "ADD_CART_ITEM",
  CLEAR_ITEM_FROM_CART: "CLEAR_ITEM_FROM_CART",
  DELETE_ITEM: 'DELETE_ITEM',
  CLEAR_CART:"CLEAR_CART"
};
